# Generated by Django 6.0 on 2025-12-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_owned",
            field=models.BooleanField(default=False),
        ),
    ]
