# Generated by Django 6.0 on 2025-12-07 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_options_alter_account_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        max_length=10,
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="Amount in sats")),
                (
                    "quote_id",
                    models.CharField(
                        help_text="Cashu mint/melt quote ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("invoice", models.TextField(help_text="Lightning invoice (bolt11)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["quote_id"], name="accounts_pa_quote_i_67e599_idx"
                    ),
                    models.Index(
                        fields=["account", "status"],
                        name="accounts_pa_account_6f031f_idx",
                    ),
                ],
            },
        ),
    ]
